Repository input-output-hk/cardano-sl, pull requests merged in 2018-05, with the labels that each got.

#2856 [DEVOPS-817] Fix appveyor build on release branch and bump cabal version
  appveyor.yml
  auxx/cardano-sl-auxx.cabal
  binary/cardano-sl-binary.cabal
  block/cardano-sl-block.cabal
  client/cardano-sl-client.cabal
  core/cardano-sl-core.cabal
  crypto/cardano-sl-crypto.cabal
  db/cardano-sl-db.cabal
  delegation/cardano-sl-delegation.cabal
  explorer/cardano-sl-explorer.cabal
  generator/cardano-sl-generator.cabal
  infra/cardano-sl-infra.cabal
  lib/cardano-sl.cabal
  lrc/cardano-sl-lrc.cabal
  networking/cardano-sl-networking.cabal
  node/cardano-sl-node.cabal
  pkgs/default.nix
  ssc/cardano-sl-ssc.cabal
  tools/cardano-sl-tools.cabal
  txp/cardano-sl-txp.cabal
  update/cardano-sl-update.cabal
  util/cardano-sl-util.cabal
  wallet-new/cardano-sl-wallet-new.cabal
  wallet/cardano-sl-wallet.cabal
Labels: release-1.2.0

#2869 successful compilation on FreeBSD; no systemd
  lib/cardano-sl.cabal
Labels: bug

#2876 [CSL-2503] implement the node-ipc server
  explorer/src/Pos/Explorer/Web/Server.hs
  infra/Pos/Shutdown/Class.hs
  lib/Setup.hs
  lib/cardano-sl.cabal
  lib/src/Pos/Web/Server.hs
  node-ipc/LICENSE
  node-ipc/Setup.hs
  node-ipc/node-ipc.cabal
  node-ipc/server.js
  node-ipc/shell.nix
  node-ipc/src/Cardano/NodeIPC.hs
  pkgs/default.nix
  stack.yaml
  tools/src/launcher/Main.hs
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/src/Cardano/Wallet/Server/CLI.hs
  wallet-new/src/Cardano/Wallet/Server/Plugins.hs
  wallet/cardano-sl-wallet.cabal
  wallet/src/Pos/Wallet/Web/Server/Launcher.hs
  wallet/src/Pos/Wallet/Web/Server/Runner.hs
Labels: wip

#2951 [R120-17] Ensure backwards compatibility of acid-state databases (#2942)
  wallet/src/Pos/Wallet/Web/State/State.hs
  wallet/src/Pos/Wallet/Web/State/Storage.hs
  wallet/src/Pos/Wallet/Web/State/Transactions.hs
Labels: release-1.2.0

#2887 Ktor z/cbr 215/validate swagger schema
  default.nix
  pkgs/default.nix
  release.nix
  scripts/test/wallet/swaggerSchemaValidation.nix
  tools/cardano-sl-tools.cabal
  tools/src/validate-json/README.md
  tools/src/validate-json/__init__.py
  tools/src/validate-json/default.nix
  tools/src/validate-json/setup.py
  tools/src/validate-json/swagger-meta-2.0.json
  tools/src/validate-json/validate_json.py
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/generate-swagger-file/Main.hs
  wallet-new/generate-swagger-file/README.md
Labels: wip

#2966 cardano-sl-infra: replace logging with cardano-sl-util (Pos_Util_Log)
  infra/Pos/Network/Types.hs
  infra/Pos/Reporting/Methods.hs
  infra/Pos/StateLock.hs
  infra/Pos/Util/TimeLimit.hs
  infra/cardano-sl-infra.cabal
  node-ipc/node-ipc.cabal
  node-ipc/src/Cardano/NodeIPC.hs
  txp/Pos/Txp/MemState/Metrics.hs
  util/Pos/Util/Log.hs
  util/Pos/Util/LogSeverity.hs
  util/Pos/Util/LoggerConfig.hs
Labels: wip
