Repository input-output-hk/cardano-sl, pull requests merged in 2018-07, with the labels that each got.

#3166 [DEVOPS-936] Hydra CI job for stylish-haskell
  .buildkite/pipeline.yml
  default.nix
  release.nix
  scripts/check-stylish.sh
  scripts/haskell/shell-with-stylish.nix
  scripts/haskell/stylish-last-10.sh
  scripts/haskell/stylish.sh
  scripts/test/hlint.nix
  scripts/test/stylish.nix
  shell.nix
Labels: wip

#3180 [DEVOPS-779] simplify CI setup with buildkite hooks
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  pkgs/generate.sh
  scripts/check-stack2nix.sh
  scripts/ci/nix-shell.sh
Labels: wip

#3297 [DEVOPS-972] fix connectScripts evaluation on OSX
  appveyor.yml
  docker.nix
  scripts/launch/connect-to-cluster/default.nix
Labels: release-1.3.0

#3283 [CDEC-456] Remove usages of -fno-warn-orphans in lib
  client/src/Pos/Client/Txp/Network.hs
  client/src/Pos/Client/Update/Network.hs
  core/cardano-sl-core.cabal
  core/src/Pos/Core/Slotting/EpochIndex.hs
  explorer/src/Pos/Explorer/Aeson/ClientTypes.hs
  generator/src/Pos/Generator/Block/Logic.hs
  infra/cardano-sl-infra.cabal
  infra/src/Pos/Infra/Communication/Protocol.hs
  infra/src/Pos/Infra/Communication/Relay/Logic.hs
  infra/src/Pos/Infra/Communication/Types/Protocol.hs
  infra/src/Pos/Infra/Communication/Types/Relay.hs
  infra/src/Pos/Infra/DHT/Workers.hs
  infra/src/Pos/Infra/Diffusion/Subscription/Common.hs
  infra/src/Pos/Infra/Diffusion/Subscription/Dns.hs
  infra/src/Pos/Infra/Recovery/Info.hs
  infra/src/Pos/Infra/Recovery/Types.hs
  infra/src/Pos/Infra/Slotting/Util.hs
  lib/bench/Bench/Pos/Diffusion/BlockDownload.hs
  lib/cardano-sl.cabal
  lib/src/Pos/Aeson.hs
  lib/src/Pos/Aeson/Types.hs
  lib/src/Pos/Communication/Message.hs
  lib/src/Pos/Context/Context.hs
  lib/src/Pos/Diffusion/Full/Block.hs
  lib/src/Pos/Diffusion/Full/Delegation.hs
  lib/src/Pos/Diffusion/Full/Ssc.hs
  lib/src/Pos/Diffusion/Full/Txp.hs
  lib/src/Pos/Diffusion/Full/Update.hs
  lib/src/Pos/Launcher/Runner.hs
  lib/src/Pos/Listener/Update.hs
  lib/src/Pos/Logic/Full.hs
  lib/src/Pos/Network/Block/Retrieval.hs
  lib/src/Pos/Network/Block/Types.hs
  lib/src/Pos/Network/Block/WorkMode.hs
  lib/src/Pos/Recovery.hs
  lib/src/Pos/Recovery/Instance.hs
  lib/src/Pos/Recovery/Types.hs
  lib/src/Pos/Web/Server.hs
  lib/src/Pos/Web/Types.hs
  lib/src/Pos/WorkMode/Class.hs
  lib/src/Pos/Worker.hs
  lib/src/Pos/Worker/Ssc.hs
  lib/src/Test/Pos/Helpers.hs
  networking/cardano-sl-networking.cabal
  networking/examples/Discovery.hs
  networking/src/Node/Message/Class.hs
  pkgs/default.nix
  wallet/src/Pos/Wallet/Web/Mode.hs
  wallet/src/Pos/Wallet/Web/Pending/Worker.hs
  wallet/test/Test/Pos/Wallet/Web/Mode.hs
Labels: wip

#3309 [RCD-32] reduce logging verbosity
  log-configs/daedalus.yaml
Labels: git-flow hotfix, needs-backporting-to, Ðëvëlöp

#3324 added unspent transaction outputs endpoint to explorer
  explorer/src/Pos/Explorer/Aeson/ClientTypes.hs
  explorer/src/Pos/Explorer/Web/Api.hs
  explorer/src/Pos/Explorer/Web/ClientTypes.hs
  explorer/src/Pos/Explorer/Web/Server.hs
  explorer/src/Pos/Explorer/Web/TestServer.hs
  explorer/src/documentation/Main.hs
  lib/configuration.yaml
  lib/src/Pos/Configuration.hs
Labels: just need CI to pass, somebody review plz

#3315 [DEVOPS-978] Add option to demo cluster to disable client auth
  default.nix
  docs/how-to/demo-cluster.md
  scripts/README.md
  scripts/launch/connect-to-cluster/default.nix
  scripts/launch/demo-cluster/default.nix
  scripts/launch/demo-nix.sh
Labels: release-1.3.0
