Repository input-output-hk/cardano-sl, pull requests merged in 2018-09, with the labels that each got.

#3534 [CBR-275] cleanup interface required for structured logging
  auxx/src/Command/Update.hs
  wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
Labels: wip

#3533 [CBR-275] stack logging ontop of 'katip', provides structured logging
  .gitignore
  core/src/Pos/Core/Util/LogSafe.hs
  db/src/Pos/DB/Update/Logic/Global.hs
  explorer/src/Pos/Explorer/ExplorerMode.hs
  explorer/src/Pos/Explorer/Socket/App.hs
  explorer/test/Test/Pos/Explorer/Socket/MethodsSpec.hs
  generator/app/VerificationBench.hs
  generator/bench/Bench/Pos/Criterion/Block/Logic.hs
  generator/cardano-sl-generator.cabal
  generator/test/Test/Pos/Binary/CommunicationSpec.hs
  generator/test/Test/Pos/Block/Logic/VarSpec.hs
  infra/src/Pos/Infra/Network/Types.hs
  infra/src/Pos/Infra/Reporting/Wlog.hs
  infra/src/Pos/Infra/Slotting/Util.hs
  lib/bench/Bench/Pos/Diffusion/BlockDownload.hs
  lib/configuration.yaml
  lib/src/Pos/Diffusion/Full.hs
  lib/src/Pos/Launcher/Resource.hs
  lib/src/Pos/Launcher/Scenario.hs
  lib/test/Test/Pos/Diffusion/BlockSpec.hs
  lib/test/Test/Pos/Launcher/ConfigurationSpec.hs
  networking/cardano-sl-networking.cabal
  networking/src/Bench/Network/Commons.hs
  networking/src/Network/Broadcast/OutboundQueue/Demo.hs
  networking/test/Test/NodeSpec.hs
  pkgs/default.nix
  scripts/bench/runbench.sh
  scripts/common-functions.sh
  scripts/launch/demo-cluster/default.nix
  scripts/test/wallet/integration/default.nix
  tools/src/dbgen/Main.hs
  tools/src/keygen/Main.hs
  tools/src/launcher/Main.hs
  util/cardano-sl-util.cabal
  util/src/Pos/Util/Log.hs
  util/src/Pos/Util/Log/Internal.hs
  util/src/Pos/Util/Log/LogSafe.hs
  util/src/Pos/Util/Log/LoggerConfig.hs
  util/src/Pos/Util/Log/Rotator.hs
  util/src/Pos/Util/Trace.hs
  util/src/Pos/Util/Wlog.hs
  util/src/Pos/Util/Wlog/Compatibility.hs
  util/test/Test/Pos/Util/LogSpec.hs
  util/test/Test/Pos/Util/WlogSpec.hs
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/integration/TransactionSpecs.hs
  wallet-new/src/Cardano/Wallet/Kernel/Keystore.hs
  wallet-new/test/InternalAPISpec.hs
  wallet/src/Pos/Wallet/Web/Pending/Worker.hs
  wallet/test/Test/Pos/Wallet/Web/AddressSpec.hs
  wallet/test/Test/Pos/Wallet/Web/Methods/BackupDefaultAddressesSpec.hs
  wallet/test/Test/Pos/Wallet/Web/Methods/LogicSpec.hs
  wallet/test/Test/Pos/Wallet/Web/Methods/PaymentSpec.hs
  wallet/test/Test/Pos/Wallet/Web/Tracking/SyncSpec.hs
Labels: release-1.4.0

#3265 [release/1.3.1] [DEVOPS-398] Testnet genesis data
  lib/configuration.yaml
  lib/testnet-genesis.json
Labels: git-flow hotfix, release-1.3.1

#3494 [DEVOPS-998] ChangeLog for 1.3.1
  CHANGELOG.md
Labels: release-1.3.1
