Repository input-output-hk/cardano-sl, pull requests merged in 2018-04, with the labels that each got.

#2729 [CSL-2422] Create initial prototype for the WalletActiveLayer.
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/server/Cardano/Wallet/API/V1/Handlers.hs
  wallet-new/server/Cardano/Wallet/Server.hs
  wallet-new/server/Cardano/Wallet/Server/Plugins.hs
  wallet-new/server/Main.hs
  wallet-new/src/Cardano/Wallet/Kernel.hs
  wallet-new/src/Cardano/Wallet/Kernel/Mode.hs
  wallet-new/src/Cardano/Wallet/WalletLayer.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
Labels: just need CI to pass

#2754 [CBR-90] Asynchronous restoration of a wallet
  .gitignore
  client/src/Pos/Client/Txp/History.hs
  pkgs/default.nix
  tools/cardano-sl-tools.cabal
  tools/src/dbgen/Lib.hs
  tools/src/dbgen/Main.hs
  tools/src/dbgen/Rendering.hs
  txp/Pos/Txp/DB/Utxo.hs
  util/Pos/Util/Util.hs
  wallet-new/bench/Bench/Cardano/Wallet/Random.hs
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/integration/Main.hs
  wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Addresses.hs
  wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Transactions.hs
  wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
  wallet-new/server/Cardano/Wallet/API/V1/Swagger/Example.hs
  wallet-new/server/Cardano/Wallet/Server/Plugins.hs
  wallet-new/server/Main.hs
  wallet-new/src/Cardano/Wallet/API/Types/UnitOfMeasure.hs
  wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
  wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
  wallet-new/src/Cardano/Wallet/API/V1/Types.hs
  wallet-new/test/APISpec.hs
  wallet-new/test/MarshallingSpec.hs
  wallet/cardano-sl-wallet.cabal
  wallet/node/Main.hs
  wallet/src/Pos/Wallet/Aeson/Storage.hs
  wallet/src/Pos/Wallet/Web/Methods/Backup.hs
  wallet/src/Pos/Wallet/Web/Methods/Logic.hs
  wallet/src/Pos/Wallet/Web/Methods/Payment.hs
  wallet/src/Pos/Wallet/Web/Methods/Restore.hs
  wallet/src/Pos/Wallet/Web/Mode.hs
  wallet/src/Pos/Wallet/Web/Server/Handlers.hs
  wallet/src/Pos/Wallet/Web/Server/Launcher.hs
  wallet/src/Pos/Wallet/Web/Server/Runner.hs
  wallet/src/Pos/Wallet/Web/State.hs
  wallet/src/Pos/Wallet/Web/State/Acidic.hs
  wallet/src/Pos/Wallet/Web/State/State.hs
  wallet/src/Pos/Wallet/Web/State/Storage.hs
  wallet/src/Pos/Wallet/Web/State/Transactions.hs
  wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
  wallet/src/Pos/Wallet/Web/Tracking/Decrypt.hs
  wallet/src/Pos/Wallet/Web/Tracking/Restore.hs
  wallet/src/Pos/Wallet/Web/Tracking/Sync.hs
  wallet/src/Pos/Wallet/Web/Tracking/Types.hs
  wallet/test/Test/Pos/Wallet/MigrationSpec.hs
  wallet/test/Test/Pos/Wallet/Web/Methods/BackupDefaultAddressesSpec.hs
  wallet/test/Test/Pos/Wallet/Web/Methods/PaymentSpec.hs
  wallet/test/Test/Pos/Wallet/Web/Mode.hs
  wallet/test/Test/Pos/Wallet/Web/Tracking/SyncSpec.hs
Labels: release-1.2.0

#2760 [CBR-119] Ugly fix to avoid some OOM problems on Explorer
  explorer/src/Pos/Explorer/Web/Server.hs
Labels: release-1.2.0

#2783 Backport PR#2674 [CSL-2374] from `release/1.1.1` to `develop`
  infra/Pos/Reporting/Methods.hs
  infra/cardano-sl-infra.cabal
  pkgs/default.nix
  stack.yaml
  tools/src/launcher/Main.hs
  wallet/src/Pos/Wallet/Web/Tracking/BListener.hs
Labels: release-1.2.0

#2763 [DEVOPS-758] Merge branch master into develop
  CHANGELOG.md
  auxx/cardano-sl-auxx.cabal
  binary/cardano-sl-binary.cabal
  block/cardano-sl-block.cabal
  client/cardano-sl-client.cabal
  core/cardano-sl-core.cabal
  crypto/cardano-sl-crypto.cabal
  db/cardano-sl-db.cabal
  delegation/cardano-sl-delegation.cabal
  explorer/cardano-sl-explorer.cabal
  generator/cardano-sl-generator.cabal
  infra/cardano-sl-infra.cabal
  lib/cardano-sl.cabal
  lib/configuration.yaml
  lrc/cardano-sl-lrc.cabal
  networking/cardano-sl-networking.cabal
  node/cardano-sl-node.cabal
  pkgs/default.nix
  ssc/cardano-sl-ssc.cabal
  stack.yaml
  tools/cardano-sl-tools.cabal
  txp/cardano-sl-txp.cabal
  update/cardano-sl-update.cabal
  util/cardano-sl-util.cabal
  wallet-new/cardano-sl-wallet-new.cabal
  wallet/cardano-sl-wallet.cabal
Labels: release-1.2.0

#2781 applicationVersion bumps for the 1.2.0 release
  lib/configuration.yaml
Labels: release-1.2.0

#2758 [CSL-2423] Implement WalletActiveLayer for wallets and accounts.
  pkgs/default.nix
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
  wallet-new/src/Cardano/Wallet/WalletLayer.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/README.md
  wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
Labels: somebody review plz

#2588 crypto: Break Arbitrary instances out into a separate package
  core/Pos/Arbitrary/Core.hs
  core/Pos/Arbitrary/Core/Unsafe.hs
  core/cardano-sl-core.cabal
  crypto/cardano-sl-crypto.cabal
  crypto/tests/LICENSE
  crypto/tests/Setup.hs
  crypto/tests/Test/Pos/Crypto/Arbitrary.hs
  crypto/tests/Test/Pos/Crypto/Arbitrary/Unsafe.hs
  crypto/tests/cardano-sl-crypto-test.cabal
  lib/cardano-sl.cabal
  lib/src/Pos/Util/UserSecret.hs
  lib/test/Test/Pos/Cbor/CborSpec.hs
  lib/test/Test/Pos/CryptoSpec.hs
  pkgs/default.nix
  ssc/Pos/Arbitrary/Ssc.hs
  ssc/cardano-sl-ssc.cabal
  stack.yaml
  txp/Pos/Arbitrary/Txp.hs
  txp/cardano-sl-txp.cabal
  update/Pos/Arbitrary/Update/Core.hs
  update/Pos/Arbitrary/Update/MemState.hs
  update/cardano-sl-update.cabal
Labels: somebody review plz

#2718 [CSLD-162] Add few use-cases to the API doc
  pkgs/default.nix
  wallet-new/README.md
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/redoc-dist/redoc.min.js
  wallet-new/server/Cardano/Wallet/API/V1/Swagger.hs
  wallet-new/server/Cardano/Wallet/LegacyServer.hs
  wallet-new/server/Cardano/Wallet/Server.hs
  wallet-new/src/Cardano/Wallet/API/V1/Types.hs
Labels: needs-backporting-to, release-1.2.0

#2728 [CSL-2398] Integration tests in CI
  .gitignore
  pkgs/default.nix
  scripts/clean/db.sh
  scripts/launch/demo.sh
  scripts/launch/kill-demo.sh
  scripts/test/wallet/integration.sh
  scripts/test/wallet/multi-integration.sh
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/integration/CLI.hs
  wallet-new/integration/Error.hs
  wallet-new/integration/Functions.hs
  wallet-new/integration/Main.hs
  wallet-new/integration/Types.hs
  wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Accounts.hs
  wallet-new/server/Cardano/Wallet/API/V1/LegacyHandlers/Wallets.hs
  wallet-new/server/Cardano/Wallet/Server/Plugins.hs
  wallet-new/src/Cardano/Wallet/API/V1/Errors.hs
  wallet-new/src/Cardano/Wallet/Client.hs
  wallet-new/src/Cardano/Wallet/Client/Http.hs
  wallet-new/test/Spec.hs
Labels: wip

#2794 [DEVOPS-769] v0-v1 exchange onboarding doc fixes
  docs/exchange-onboarding.md
Labels: git-flow hotfix, needs-backporting-to, Ðëvëlöp

#2810 R120 4/unicode characters support
  scripts/launch/connect-to-cluster/default.nix
  scripts/launch/connect-to-cluster/mainnet-staging.sh
  tools/src/launcher/Main.hs
  wallet-new/README.md
Labels: needs-backporting-to, release-1.2.0

#2820 Ktor z/r120 4/unicode characters support 1.2.0
  scripts/launch/connect-to-cluster/default.nix
  scripts/launch/connect-to-cluster/mainnet-staging.sh
  tools/src/launcher/Main.hs
  wallet-new/README.md
Labels: release-1.2.0

#2778 [CSL-2424] Implement WalletActiveLayer for addresses
  wallet-new/src/Cardano/Wallet/API/V1/Migration/Types.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
  wallet/src/Pos/Wallet/Web/State/State.hs
  wallet/src/Pos/Wallet/Web/State/Storage.hs
Labels: somebody review plz

#2811 [CSL-2425] Implement WalletActiveLayer for transactions
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/src/Cardano/Wallet/WalletLayer/Error.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Legacy.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Legacy/Transactions.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/QuickCheck.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Types.hs
Labels: somebody review plz
