Repository input-output-hk/cardano-sl, pull requests merged in 2018-11, with the labels that each got.

#3807 [CBR-477] flush logs before applications exit
  generator/app/VerificationBench.hs
  generator/bench/Bench/Pos/Criterion/Block/Logic.hs
  lib/src/Pos/Launcher/Resource.hs
  networking/bench/LogReader/Main.hs
  networking/bench/Receiver/Main.hs
  networking/bench/Sender/Main.hs
  networking/src/Bench/Network/Commons.hs
  networking/test/Test/Network/Broadcast/OutboundQueueSpec.hs
  tools/src/keygen/Main.hs
  tools/src/launcher/Main.hs
  util/src/Pos/Util/Wlog.hs
  util/src/Pos/Util/Wlog/Compatibility.hs
Labels: bug, release-1.4.0

#3816 [RCD-42] log-configs/cluster.yaml: Include debug messages in json log
  log-configs/cluster.yaml
Labels: release-2.0.0

#3815 [CSL-2526] update changes after covering remaining fees
  wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
  wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
  wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
  wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Active.hs
  wallet-new/test/unit/Test/Spec/CoinSelection.hs
  wallet-new/test/unit/Test/Spec/GetTransactions.hs
  wallet-new/test/unit/Test/Spec/NewPayment.hs
Labels: release-2.0.0

#3831 [DEVOPS-1121] explorer: add testnet URL to CORS origin whitelist
  explorer/src/Pos/Explorer/Socket/App.hs
Labels: release-2.0.0

#3817 [DEVOPS-1094] explorer frontend: hide footer in testnet mode
  explorer/frontend/src/Explorer/View/Footer.purs
Labels: release-2.0.0

#3820 Implement the node API without referencing `wallet-new`
  lib/src/Pos/Node/API.hs
  lib/src/Pos/Util/Servant.hs
  node/cardano-sl-node.cabal
  node/src/Cardano/Node/API.hs
  pkgs/default.nix
  wallet-new/src/Cardano/Wallet/API/Response.hs
Labels: wip

#3846 Doc fixes
  default.nix
  docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
Labels: release-2.0.0

#3855 [RCD-46] fix Prefiltering not ignoring txIds from Inputs
  wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
Labels: release-2.0.0

#3848 [DEVOPS-1130] bump versions
  lib/configuration.yaml
Labels: release-2.0.0

#3861 [RCD-45] & [RCD-44] Review fee calculation entirely
  wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/FromGeneric.hs
  wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic.hs
  wallet-new/src/Cardano/Wallet/Kernel/CoinSelection/Generic/Fees.hs
  wallet-new/test/unit/InputSelection/FromGeneric.hs
  wallet-new/test/unit/Test/Spec/CoinSelection.hs
Labels: release-2.0.0

#3867 release/2.0.0 [DEVOPS-1141] Set an ample maximum block size for epoch boundary blocks
  chain/src/Pos/Chain/Block/Logic/Integrity.hs
  lib/src/Pos/Communication/Limits.hs
Labels: release-2.0.0

#3871 [DEVOPS-1141] Bump applicationVersion for testnet_wallet
  .buildkite/windows.ps1
  lib/configuration.yaml
Labels: git-flow hotfix, release-1.3.1

#3870 [CBR-475] adds MVar for any sqlite-operation
  pkgs/default.nix
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
  wallet-new/test/unit/TxMetaStorageSpecs.hs
Labels: release-2.0.0

#3876 [RCD-47] Fix 'hasSpendingPassword' metadata recovery during migration
  wallet-new/src/Cardano/Wallet/Kernel/Migration.hs
Labels: release-2.0.0

#3879 [DEVOPS-1112] configuration.yaml: bump staging and testnet applicationVersions
  lib/configuration.yaml
Labels: release-2.0.0

#3883 [RCD-48] explorer frontend: Update testnet link in footer
  explorer/frontend/src/Explorer/View/Footer.purs
Labels: release-2.0.0

#3811 [RCD-37] ChangeLog for 2.0.0
  CHANGELOG.md
Labels: release-2.0.0

#3911 [DEVOPS-1153] Extend addWAddress to support newly-found accounts
  CHANGELOG.md
  wallet/src/Pos/Wallet/Web/State/Storage.hs
Labels: release-2.0.0

#3919 [DEVOPS-1112] Bump applicationVersion 2 -> 3 for testnet
  lib/configuration.yaml
Labels: release-2.0.0
