Repository input-output-hk/cardano-sl, pull requests merged in 2018-08, with the labels that each got.

#2939 [DEVOPS-834] Cardano faucet package
  .gitignore
  default.nix
  faucet/LICENSE
  faucet/Setup.hs
  faucet/cardano-sl-faucet.cabal
  faucet/frontend/default.nix
  faucet/frontend/index.html
  faucet/logging.cfg
  faucet/server/Main.hs
  faucet/src/Cardano/Faucet.hs
  faucet/src/Cardano/Faucet/Endpoints.hs
  faucet/src/Cardano/Faucet/Init.hs
  faucet/src/Cardano/Faucet/Metrics.hs
  faucet/src/Cardano/Faucet/Swagger.hs
  faucet/src/Cardano/Faucet/Types.hs
  faucet/src/Cardano/Faucet/Types/API.hs
  faucet/src/Cardano/Faucet/Types/Config.hs
  faucet/src/Cardano/Faucet/Types/Recaptcha.hs
  faucet/src/Cardano/WalletClient.hs
  faucet/test-config.json.template
  faucet/test/Spec.hs
  faucet/test/captcha-resp-err.json
  faucet/test/captcha-resp-ok.json
  faucet/test/multi-line-secret.txt
  faucet/test/valid-secret.txt
  faucet/wallet-source.json.template
  pkgs/default.nix
  scripts/launch/demo-cluster/default.nix
  stack.yaml
Labels: release-1.3.1

#3375 [DEVOPS-906] Merge master branch into develop
  lib/configuration.yaml
  log-configs/daedalus.yaml
Labels: release-1.3.0

#3428 [CBR-375] Create transaction metadata for incoming transactions
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/src/Cardano/Wallet/Kernel.hs
  wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/Sqlite.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/TxMeta/Types.hs
  wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
  wallet-new/src/Cardano/Wallet/Kernel/Transactions.hs
  wallet-new/src/Cardano/Wallet/Kernel/Types.hs
  wallet-new/src/Cardano/Wallet/Kernel/Util/Core.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Transactions.hs
  wallet-new/test/unit/Test/Spec/Kernel.hs
  wallet-new/test/unit/Test/Spec/TxMetaScenarios.hs
  wallet-new/test/unit/TxMetaStorageSpecs.hs
  wallet-new/test/unit/UTxO/Interpreter.hs
  wallet-new/test/unit/Wallet/Inductive/Cardano.hs
Labels: wip

#3386 [DEVOPS-999] explorer frontend: Replace @GITREV@ with actual rev
  explorer/frontend/default.nix
Labels: release-1.3.1

#3472 [DEVOPS-999] explorer frontend: Replace @gitrev@ with actual rev
  explorer/frontend/default.nix
  explorer/frontend/shell.nix
Labels: bug

#3470 Matt noonan/restoration
  wallet-new/cardano-sl-wallet-new.cabal
  wallet-new/src/Cardano/Wallet/Kernel.hs
  wallet-new/src/Cardano/Wallet/Kernel/Accounts.hs
  wallet-new/src/Cardano/Wallet/Kernel/Addresses.hs
  wallet-new/src/Cardano/Wallet/Kernel/BListener.hs
  wallet-new/src/Cardano/Wallet/Kernel/ChainState.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/AcidState.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/BlockContext.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/BlockMeta.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/HdWallet/Create.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/Resolved.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/Spec.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/Spec/Update.hs
  wallet-new/src/Cardano/Wallet/Kernel/DB/Util/AcidState.hs
  wallet-new/src/Cardano/Wallet/Kernel/Decrypt.hs
  wallet-new/src/Cardano/Wallet/Kernel/Internal.hs
  wallet-new/src/Cardano/Wallet/Kernel/NodeStateAdaptor.hs
  wallet-new/src/Cardano/Wallet/Kernel/Pending.hs
  wallet-new/src/Cardano/Wallet/Kernel/PrefilterTx.hs
  wallet-new/src/Cardano/Wallet/Kernel/Restore.hs
  wallet-new/src/Cardano/Wallet/Kernel/Types.hs
  wallet-new/src/Cardano/Wallet/Kernel/Util/Core.hs
  wallet-new/src/Cardano/Wallet/Kernel/Util/StrictList.hs
  wallet-new/src/Cardano/Wallet/Kernel/Util/StrictNonEmpty.hs
  wallet-new/src/Cardano/Wallet/Kernel/Wallets.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Conv.hs
  wallet-new/src/Cardano/Wallet/WalletLayer/Kernel/Wallets.hs
  wallet-new/test/unit/UTxO/Interpreter.hs
  wallet-new/test/unit/Wallet/Inductive/Cardano.hs
Labels: wip
